### ISSUE TITLE
Folder location of db

### ISSUE THREAD

**Issue by sebtouze** [movie-project/movie-project#25]
Hi all, 

this is a proposition for the location of the database : currently on GNU/Linux it is located inthe user's home folder. 
In fact under Gnome environment all the applications config files are located in a ~/.config/<software name> folder. I could be nice to apply this convention. 
I don't know if it's the same for KDE or other desktop environment ?

**Comment by ochurlaud** [comment]
* Still do be done for win/osx
* Pb: the app name is hardcoded

**Comment by ochurlaud** [comment]
Done for Windows. OSX during the week...

**Comment by ochurlaud** [comment]
Works! I close the issue
