### ISSUE TITLE
Make tag name a db index ?

### ISSUE THREAD

**Issue by sebtouze** [movie-project/movie-project#76]
Hi, 

I think it can be interesting to make a tag's name an index. This will avoid duplicate tag's name. 
An even better way could be to check if a tag exist with a different letters case combination. For example : "funny" is the same as "Funny" or "FUnny"

Do you think it could be useful ?

**Comment by ochurlaud** [comment]
Nope, because the database has already a constraint no duplicate (see 
the def of the db)

**Comment by sebtouze** [comment]
Yes, you're right, I checked, SQLight is case insensitive so it already works =)
